schemaVersion: 2.0
timeout: 30

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  java:
    version: 1.8
  env:
    skipTest: false

publish:
  reports:
    checkstyle: true
    pmd: true
    findbugs: true
    junit: true

pipelines:

# prb builds
- branchName: apple-0.5
  build:
    template: buildozer:v1:prb

- branchName: apple-0.5-release
  build:
    template: buildozer:v1:prb

# publish pipelines
- branchName: apple-0.5
  build:
    template: buildozer:v1:publish
  publish:
    libraries:
      repo: m2:oss-patched
  finally:
    radar:
      annotate: true

- branchName: apple-0.5-release
  build:
    template: buildozer:v1:publish
  publish:
    libraries:
      repo: m2:oss-patched
    release: true

  finally:
    radar:
      annotate: true
